# Jekyll Resume Theme

# Site settings
title: Leigh Akin Resume
email: jinx.wyvern@gmail.com
description: Leigh Akin resume for Ironworking
baseurl: "http://shitposter.ca/leigh-akin/"
url: "http://shitposter.ca/leigh-akin/"
name: Leigh Akin
job: Ironworker
location: (604)655-9287
languages: Outdoors, Wilderness and Ecology
resume_link: http:shitposter.ca/leigh-akin/docs/resume.pdf
twitter_username: wyvern_jinx
github_username:  jinx432
email_address: jinx.wyvern@gmail.com

# Build settings
markdown: kramdown
