# Jekyll Resume Theme

# Site settings
title: Leigh Akin Resume
email: jinx.wyvern@gmail.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: "http://shitposter.ca/leigh-akin/"
url: "http://shitposter.ca/leigh-akin/"
name: Leigh Akin
job: Rodbuster
location: Vancouver, CA
languages: HTML, CSS and Javascript
twitter_username: wyvern_jinx
github_username:  jinx432
email_address: jinx.wyvern@gmail.com

# Build settings
markdown: kramdown
