# Jekyll Resume Theme

# Site settings
title: Leigh Akin Resume
email: neph.xyz@gmail.com
description: Leigh Akin resume for Carpentry
baseurl: "http://hivegreen.com/leigh-akin/"
url: "http://hivegreen.com/leigh-akin/"
name: Leigh Akin
job: Carpenter
location: (604)655-9287
languages: Outdoors, Wilderness and Ecology
resume_link: "http://hivegreen.com/leigh-akin/docs/resume.pdf"
twitter_username: hivegrn
github_username:  LeighAkin
email_address: neph.xyz@gmail.com

# Build settings
markdown: kramdown
